### PR TITLE
Updated to inspectIT version 1.6.8

### PR DESCRIPTION
**Pull request by ivansenic**
@mariomann @matthias-huber Can you please check if changes are working here. I would not like to push here directly, cause I changed also the concept of attaching agent to the Jetty. What do you say?

### CODE REVIEW

**Comment by matthias-huber** [comment]
@ivansenic I tested it. From my point of view it is working.

Building Image Locally: SUCCESSFUL

Running Container with linked CMR: SUCCESSFUL
Running Container with linked CMR and specifying the agent name: SUCCESSFUL

Running Container with un-linked CMR (parameters): SUCCESSFUL
Running Container with un-linked CMR (parameters)  and specifying the agent name: SUCCESSFUL

**Comment by ivansenic** [comment]
@matthias-huber Merge then? And don't forget to tag it appropriately.

**Comment by ivansenic** [comment]
@inspectit-docker/owners Anybody else wants to push the merge button?

**Comment by ivansenic** [comment]
Changed to using `chown jetty:jetty -R $INSPECTIT_AGENT_HOME` for permissions, as jetty is started with jetty user :)

**Pull request merged**
